version: '3.3'
services:
  transitdata-cache-bootstrapper:
    image: transitdata-cache-bootstrapper
    network_mode: host
    secrets:
      - pubtrans_community_conn_string
secrets:
  pubtrans_community_conn_string:
    file: ./secrets/pubtrans_community_conn_string.secret
