@startuml

/''' Style '''/

!include local-theme.iuml


title Full graph


/''' Nodes '''/

rectangle Digitransit as digitransit {
    rectangle hslalert
    rectangle "siri2gtfsrt for Finland" as s2gfinland
    rectangle "raildigitraffic2gtfsrt for HSL" as r2ghsl
    rectangle "raildigitraffic2gtfsrt for Finland" as r2gfinland
    rectangle "OpenTripPlanner for HSL" as otphsl
    rectangle "OpenTripPlanner for Finland" as otpfinland

    usecase """https://api.digitransit.fi/realtime/raildigitraffic2gtfsrt/v1/hsl""" as r2gv1
    usecase """https://<hidden-raildigitraffic2gtfsrt-endpoint>""" as r2ghidden
    usecase """https://api.digitransit.fi/realtime/service-alerts/v1/""" as httpsav1
    usecase """https://<hidden-hslalert-endpoint>""" as hslalerthidden
    usecase """https://api.digitransit.fi/realtime/trip-updates/v1/HSL""" as httptuv1

    note "Offers also cancellation Trip Updates" as hslalertnote
}

rectangle LIJ as lij {
    rectangle PubTrans as pubtrans
    rectangle OMM as omm

    'FIXME: Uncomment, if should include vehicle positions
    'rectangle "Vehicle PC" as vpc
    'usecase """mqtts://mqtt.hsl.fi//hfp/v1/journey/#""" as hfpv1journey
}

rectangle "Trapeze input" as trapezeinput {
    rectangle Poikkeusinfo as poikkeusinfo
    rectangle Muuli as muuli

    usecase """http://www.poikkeusinfo.fi/xml/v3""" as poikkeusinfoapi
}

rectangle "Stop display systems" as stopdisplays {
    rectangle Axentia as axentia
    rectangle Mono as mono
}

rectangle transitdata as transitdata {
    together {
        rectangle "Pulsar processing" as pulsar

        usecase """mqtts://mqtt.hsl.fi/gtfsrt/v2/fi/hsl/tu/#""" as mqttgtfsrtv2tu
        usecase """mqtts://mqtt.hsl.fi/gtfsrt/v2/fi/hsl/sa/#""" as mqttgtfsrtv2sa
        usecase """https://dev.hsl.fi/gtfs-realtime/v1/trip-updates/""" as pulsarhttpgtfsrtv1tu
        usecase """https://dev.hsl.fi/gtfs-realtime/v1/service-alerts/""" as pulsarhttpgtfsrtv1sa

        'FIXME: Uncomment, if should include vehicle positions
        'usecase """mqtts://mqtt.hsl.fi/gtfsrt/v2/fi/hsl/vp/#""" as mqttgtfsrtv2vp
        'usecase """https://dev.hsl.fi/gtfs-realtime/v1/vehicle-positions/""" as pulsarhttpgtfsrtv1vp
    }

    together {
        rectangle roisto
        rectangle bessersmith

        usecase """mqtts://mqtt.hsl.fi/gtfsrt/v1/fi/hsl/tu""" as mqttgtfsrtv1tu
        usecase """mqtts://mqtt.hsl.fi/mono/v2/#""" as mqttmonov2
        usecase """mqtts://mqtt.hsl.fi/mono/v3/#""" as mqttmonov3

        note "Does not offer cancellation Trip Updates" as bessersmithnote
    }
}

rectangle "Finnish Transport Agency" as fta {
    usecase "Digitraffic APIs" as digitrafficapis
}

actor "HSL communications professional" as comms
actor "Operator" as operator


/''' Edges '''/

digitrafficapis -down-> r2gfinland
digitrafficapis -down-> r2ghsl
r2gfinland -down-> r2gv1
r2ghsl -down-> r2ghidden
r2ghidden -down-> otphsl
r2gv1 -down-> s2gfinland
mqttgtfsrtv1tu -down-> otphsl

muuli -down-> poikkeusinfo
poikkeusinfo -down-> poikkeusinfoapi
poikkeusinfoapi -down-> hslalert
hslalert -down-> httpsav1
hslalert -down-> hslalerthidden

httpsav1 -down-> s2gfinland
s2gfinland -down-> httptuv1
httptuv1 -down-> otpfinland

hslalerthidden -down-> pulsar

pubtrans -down-> roisto
roisto -down-> mqttmonov2
roisto -down-> mqttmonov3
mqttmonov2 -down-> mono
mqttmonov3 -down-> bessersmith
bessersmith -down-> mqttgtfsrtv1tu
mqttgtfsrtv1tu -down-> axentia

omm -down-> pubtrans
omm -down-> pulsar
pubtrans -down-> pulsar
digitrafficapis -down-> pulsar

pulsar -down-> mqttgtfsrtv2tu
pulsar -down-> mqttgtfsrtv2sa

mqttgtfsrtv2tu -down-> mono
mqttgtfsrtv2sa -down-> mono
mqttgtfsrtv2tu -down-> axentia
mqttgtfsrtv2sa -down-> axentia
mqttgtfsrtv2tu -down-> otphsl
mqttgtfsrtv2sa -down-> otphsl
mqttgtfsrtv2tu -down-> otpfinland
mqttgtfsrtv2sa -down-> otpfinland

'FIXME: Uncomment, if should include vehicle positions
'vpc -down-> hfpv1journey
'hfpv1journey -down-> pulsar
'pulsar -down-> mqttgtfsrtv2vp
'pulsar -down-> pulsarhttpgtfsrtv1vp

pulsar -down-> pulsarhttpgtfsrtv1tu
pulsar -down-> pulsarhttpgtfsrtv1sa

pulsarhttpgtfsrtv1sa -down-> httpsav1
pulsarhttpgtfsrtv1tu -down-> httptuv1

httpsav1 -down-> otphsl

comms -down-> poikkeusinfo
comms -down-> omm
operator -down-> muuli
operator -down-> omm

hslalertnote .. httpsav1
hslalertnote .. hslalerthidden
bessersmithnote .. mqttgtfsrtv1tu

@enduml
