@startuml

!includeurl https://cdn.jsdelivr.net/gh/HSLdevcom/hsl-plantuml-theme/hsl-theme.iuml

' To visually separate interfaces
skinparam Usecase {
    BackgroundColor #ffffff
    BorderColor #f092cd
}

@enduml
