@startgantt

[Deploy Pulsar PubTrans Trip Update processing] as [deployptu] lasts 5 days
[Poll ""service-alerts.v1"" into Pulsar as hslalert-source] as [sapoll] lasts 3 days
[Design MQTT topic ""gtfsrt.v2.fi.hsl.tu.#""] as [designmqtttuv2] lasts 3 days
[Document ""gtfsrt.v2.fi.hsl.tu.#"" into digitransit.fi] as [documentmqtttuv2] lasts 1 days
[Document ""service-alerts.v1"" losing Trip Updates into digitransit.fi] as [documentsav1losetu] lasts 1 days
[Merge Trip Updates from hslalert-source and Pubtrans processing] as [mergetu] lasts 2 days
[Release ""gtfsrt.v2.fi.hsl.tu.#""] as [releasemqtttuv2] lasts 1 days
[Develop ""DIFFERENTIAL"" GTFS cancellation Trip Update support into Axentia systems] as [axentiatu] lasts 5 days
[Develop ""DIFFERENTIAL"" GTFS prediction and cancellation Trip Update support into Mono] as [monotu] lasts 5 days
[Configure HSL OTP service to use ""gtfsrt.v2.fi.hsl.tu.#""] as [hslotpmqttv2] lasts 1 days
[Deploy Axentia cancellation Trip Update support] as [axentiatudeploy] lasts 1 days
[Deploy Mono Trip Update support] as [monotudeploy] lasts 1 days
[Leave ""gtfsrt.v1.fi.hsl.tu"" undocumented in digitransit.fi and kill after a while] as [killtuv1] lasts 30 days

[sapoll] -> [mergetu]
[deployptu] -> [mergetu]
[designmqtttuv2] -> [documentmqtttuv2]
[designmqtttuv2] -> [documentsav1losetu]
[mergetu] -> [releasemqtttuv2]
[documentmqtttuv2] -> [releasemqtttuv2]
[documentsav1losetu] -> [releasemqtttuv2]
[axentiatu] -> [axentiatudeploy]
[monotu] -> [monotudeploy]
[releasemqtttuv2] -> [killtuv1]
[releasemqtttuv2] -> [hslotpmqttv2]
[releasemqtttuv2] -> [axentiatudeploy]
[releasemqtttuv2] -> [monotudeploy]
-- Finish step 1 --
[Start training operators to cancel trips in OMM] as [startoptraining] lasts 90 days
[hslotpmqttv2] -> [startoptraining]
[axentiatudeploy] -> [startoptraining]
[monotudeploy] -> [startoptraining]

@endgantt
